package com.github.iojjj.bootstrap.authorization.oauth;

/**
 * List of default OAuth API providers.
 */
public enum BSOAuthApi {
    AWEBBER,
    DIGG,
    DOKTORNARABOTE,
    FACEBOOK,
    FLICKR,
    FOURSQUARE2,
    FOURSQUARE,
    FREELANCER,
    GENIUS,
    GITHUB,
    GOOGLE,
    HH,
    IMGUR,
    KAIXIN,
    LINKEDIN,
    LINKEDIN2,
    LIVE,
    MAILRU,
    MEETUP,
    MISFIT,
    NAVER,
    NETEASE_WEIBOO,
    ODNOKLASSNIKI,
    PINTEREST,
    PX500,
    RENREN,
    SALESFORCE,
    SINA_WEIBO,
    SINA_WEIBO2,
    SKYROCK,
    SOHU_WEIBO,
    STACK_EXCHANGE,
    TRELLO,
    TUMBLR,
    TUTBY,
    TWITTER,
    VIADEO,
    VKONTAKTE,
    XING,
    YAHOO
}
